# https://docs.pytest.org/en/stable/customize.html
[tool.pytest.ini_options]
addopts = "--alluredir allure-results"
filterwarnings = "ignore::DeprecationWarning"
markers = [
    "main_page",
    "reminders_list_page",
    "reminder_list_info_page",
    "reminder_page"
    ]
